# services/init_db.py
import sqlite3
import os

# Define path to the database
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_DIR, "db", "mindmate.db")

def get_db_connection():
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    return sqlite3.connect(DB_PATH)

def init_db():
    conn = get_db_connection()
    cur = conn.cursor()
    
    # 1. USERS TABLE
    cur.execute("""
        CREATE TABLE IF NOT EXISTS users (
            user_id TEXT PRIMARY KEY,
            password_hash TEXT NOT NULL,
            wake_word TEXT DEFAULT 'mindmate',
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # --- 🟢 AUTO-CREATE DEFAULT USER ---
    cur.execute("SELECT user_id FROM users WHERE user_id = 'admin'")
    if not cur.fetchone():
        cur.execute("INSERT INTO users (user_id, password_hash) VALUES (?, ?)", ('admin', 'admin'))
        print("👤 Default user 'admin' created (Password: admin)")

    # 2. EVENTS TABLE (Calendar / History)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT,
            title TEXT,
            category TEXT,
            start_time TEXT,
            end_time TEXT,
            location_id INTEGER,
            location_name TEXT,
            FOREIGN KEY(user_id) REFERENCES users(user_id)
        )
    """)

    # 3. NOTES TABLE (Knowledge / Facts / Summaries)
    # 🟢 NEW: Dedicated table for storing learned notes with headings & categories
    cur.execute("""
        CREATE TABLE IF NOT EXISTS notes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT,
            category TEXT,       -- e.g. "Work", "Personal", "Study"
            title TEXT,          -- The "Heading" generated by AI
            summary TEXT,        -- The "Summary" of the note
            original_text TEXT,  -- The raw input for context
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(user_id)
        )
    """)

    # 4. MEMORIES TABLE (Legacy / Long-term patterns)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS memories (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT,
            memory_type TEXT,
            title TEXT,
            content TEXT,
            confidence_score REAL,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            last_reinforced DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(user_id)
        )
    """)

    # 5. CHAT MESSAGES TABLE
    cur.execute("""
        CREATE TABLE IF NOT EXISTS chat_messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT,
            sender TEXT,
            text TEXT,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(user_id)
        )
    """)

    # 6. LOCATIONS TABLE
    cur.execute("""
        CREATE TABLE IF NOT EXISTS locations (
            location_id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT,
            name TEXT
        )
    """)
    
    # 7. REMINDERS TABLE
    cur.execute("""
        CREATE TABLE IF NOT EXISTS reminders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT,
            event_id INTEGER,
            message TEXT,
            trigger_time TEXT,
            status TEXT DEFAULT 'pending',
            recurrence_rule TEXT,
            priority_level TEXT,
            FOREIGN KEY(event_id) REFERENCES events(id)
        )
    """)

    # 8. VOICE ANALYSIS TABLE
    cur.execute("""
        CREATE TABLE IF NOT EXISTS voice_analysis (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT,
            associated_event_id INTEGER,
            original_transcript TEXT,
            emotion_label TEXT,
            stress_level REAL,
            FOREIGN KEY(associated_event_id) REFERENCES events(id)
        )
    """)

    # --- MIGRATION CHECK (For existing DBs) ---
    # Attempt to add columns if they are missing in older DB versions
    try:
        cur.execute("ALTER TABLE events ADD COLUMN location_name TEXT")
        print("✅ Added 'location_name' column to events.")
    except sqlite3.OperationalError: pass 

    try:
        cur.execute("ALTER TABLE memories ADD COLUMN title TEXT")
        print("✅ Added 'title' column to memories.")
    except sqlite3.OperationalError: pass

    conn.commit()
    conn.close()
    print("✅ Database initialized successfully (with 'notes' table).")

if __name__ == "__main__":
    init_db()