# models/train_user_habit_model.py
"""
Trains a per-user habit model from the CSV generated by prepare_data.py.
Saves {user_id}.pkl to models/users/.

Run:
  python models/train_user_habit_model.py
  OR called automatically by trainer.py weekly.
"""

import os
import sys
import pandas as pd
import joblib
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

USERS_DIR = os.path.join(os.path.dirname(__file__), "users")


def train_user_model(user_id: str) -> bool:
    csv_path   = os.path.join(USERS_DIR, f"{user_id}_data.csv")
    model_path = os.path.join(USERS_DIR, f"{user_id}.pkl")

    if not os.path.exists(csv_path):
        print(f"❌ CSV not found for {user_id}. Run prepare_data.py first.")
        return False

    df = pd.read_csv(csv_path)

    if df.empty or "activity" not in df.columns:
        print(f"❌ CSV empty or missing 'activity' column.")
        return False

    # Drop rows with missing required features
    required = ["Hour", "DayOfWeek", "Month", "activity"]
    df = df.dropna(subset=required)

    if len(df) < 5:
        print(f"⚠️  Only {len(df)} rows — need at least 5 to train. Skipping.")
        return False

    # ── Feature engineering ───────────────────────────────────────────────────
    import numpy as np
    df["hour_sin"]    = np.sin(2 * np.pi * df["Hour"] / 24)
    df["hour_cos"]    = np.cos(2 * np.pi * df["Hour"] / 24)
    df["day_sin"]     = np.sin(2 * np.pi * df["DayOfWeek"] / 7)
    df["day_cos"]     = np.cos(2 * np.pi * df["DayOfWeek"] / 7)
    df["duration_min"] = df.get("duration_min", pd.Series([30]*len(df))).fillna(30)

    features = ["Hour", "DayOfWeek", "Month",
                "hour_sin", "hour_cos", "day_sin", "day_cos", "duration_min"]
    X = df[features]
    
    le = LabelEncoder()
    y  = le.fit_transform(df["activity"])

    # ── Train ─────────────────────────────────────────────────────────────────
    if len(df) >= 20:
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42)
        model = RandomForestClassifier(n_estimators=150, random_state=42)
        model.fit(X_train, y_train)
        acc = accuracy_score(y_test, model.predict(X_test))
        print(f"✅ Model trained for {user_id}  |  accuracy={acc:.2%}  |  {len(df)} rows")
    else:
        model = RandomForestClassifier(n_estimators=50, random_state=42)
        model.fit(X, y)
        print(f"✅ Model trained for {user_id}  |  {len(df)} rows (small dataset)")

    # ── Save ──────────────────────────────────────────────────────────────────
    joblib.dump({"model": model, "encoder": le, "features": features}, model_path)
    print(f"💾 Saved → {model_path}")
    return True


if __name__ == "__main__":
    train_user_model("meanonymus87@gmail.com")